//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Client.rc
//
#define IDR_MANIFEST                    1
#define IDC_TOOLBAR                     100
#define IDB_EDIT                        100
#define IDD_MAIN                        100
#define IDA_MAIN                        100
#define IDI_MAIN                        100
#define IDI_CLIENT                      100
#define IDB_TAB                         101
#define IDI_SMALL                       101
#define IDD_SERVER                      101
#define IDM_RICHEDIT                    101
#define IDB_SEND                        102
#define IDD_LIST                        102
#define IDD_USER                        103
#define IDD_CHANNEL                     104
#define IDC_JOIN                        104
#define IDD_TOPIC                       110
#define IDD_SPLASHRTFEDITOR             111
#define IDB_MAN                         133
#define IDM_LOG                         134
#define IDM_TAB                         136
#define IDM_CHANNEL                     137
#define IDB_STATUS                      139
#define IDB_STATUSIMG                   148
#define IDB_UL_BG                       149
#define IDB_UL_SEL                      150
#define IDD_SPLASHRTF                   150
#define IDB_UL_HOT                      151
#define IDB_UL_FOC                      152
#define IDR_USER                        157
#define IDM_USER                        157
#define IDR_ACCELERATOR1                159
#define IDA_RICHEDIT                    159
#define IDD_MSGSEND                     161
#define IDD_MSGRECV                     162
#define IDR_MENU1                       168
#define IDM_CHANLIST                    168
#define IDM_USER1                       169
#define IDM_USERGOD                     169
#define idsRtfCmd                       200
#define idsBold                         201
#define idsItalic                       202
#define idsUnderline                    203
#define idsSubscript                    204
#define idsSuperscript                  205
#define idsFont                         206
#define idsFrColor                      207
#define idsFgColor                      207
#define idsBgColor                      208
#define idsSheetColor                   209
#define idsAlignLeft                    210
#define idsAlignRight                   211
#define idsAlignCenter                  212
#define idsAlignJustify                 213
#define idsMarksBullet                  214
#define idsMarksArabic                  215
#define idsStartIndentInc               216
#define idsStartIndentDec               217
#define idsBkMode                       218
#define IDS_MSG_NICKERROR               500
#define IDS_MSG_NICKVALID               501
#define IDS_MSG_NICKNONPRINT            502
#define IDS_MSG_NICKEMPTY               503
#define IDS_MSG_TABCLOSE                505
#define IDS_MSG_PRIVATETALK             510
#define IDS_MSG_PRIVATEMESSAGE          511
#define IDS_MSG_ALERT                   512
#define IDS_MSG_SOUNDSIGNAL             513
#define IDS_MSG_CLIPBOARD               514
#define IDS_MSG_SPLASHRTF               515
#define IDS_MSG_KICK                    516
#define IDS_MSG_EDITOR                  517
#define IDS_MSG_LIMITCHATLINE           518
#define IDS_MSG_READER                  520
#define IDC_LOG                         1001
#define IDC_USERLIST                    1002
#define IDC_RICHEDIT                    1003
#define IDC_CHANLIST                    1004
#define IDC_TAB                         1005
#define IDC_HOST                        1010
#define IDC_PORT                        1011
#define IDC_JOINPASS                    1016
#define IDC_PASS                        1033
#define IDC_JOINCHAN                    1034
#define IDC_REFRESHLIST                 1036
#define IDC_MSGSPIN                     1038
#define IDC_USERMODE                    1039
#define IDC_MODE                        1039
#define IDC_STATUS                      1039
#define IDC_STATUSIMG                   1040
#define IDC_STATUSMSG                   1041
#define IDC_TOPICTEXT                   1045
#define IDC_STATIC1                     1046
#define IDC_STATIC2                     1047
#define IDC_STATIC3                     1048
#define IDC_STATIC4                     1049
#define IDC_STATIC5                     1050
#define IDC_AUTOCLOSE                   1052
#define IDC_AUTOCLOSESPIN               1053
#define IDC_RICHEDIT21                  1054
#define IDC_CHECK1                      1056
#define IDC_DATETIMEPICKER1             1058
#define IDC_RECVTIME                    1058
#define IDC_REPLY                       1059
#define IDC_MSGSPINBLUE                 1060
#define IDC_MSGSPINBLUE2                1062
#define IDC_MSGSPINRED                  1062
#define IDC_NICK                        40002
#define IDC_CONNECT                     40004
#define IDC_SENDBYENTER                 40017
#define IDC_SENDBYCTRLENTER             40018
#define IDC_SEND                        40025
#define IDOK2                           40026
#define IDC_CUT                         40030
#define IDC_PASTE                       40031
#define IDC_DELETE                      40032
#define IDC_SELECTALL                   40033
#define IDC_CLOSE                       40034
#define IDC_COPY                        40036
#define IDC_CLEARLOG                    40039
#define IDC_LOGCLEAR                    40040
#define IDC_LOGCOPY                     40041
#define IDC_TABCLOSE                    40043
#define IDC_CHANTOPIC                   40048
#define ID_OVERLAP_PRIVATETALK          40049
#define ID_OVERLAP_SPLASHMESSAGE        40050
#define IDC_PRIVATETALK                 40051
#define IDC_SPLASHRTF                   40052
#define ID_OVERLAP_ACCESSRIGHTS         40053
#define ID_ACCESSRIGHTS_FOUNDER         40054
#define ID_ACCESSRIGHTS_FOUNDER40055    40055
#define ID_ACCESSRIGHTS_ADMINISTRATOR   40056
#define ID_ACCESSRIGHTS_ADMINISTRATOR40057 40057
#define ID_ACCESSRIGHTS_MODERATOR       40058
#define ID_ACCESSRIGHTS_MEMBER          40059
#define ID_ACCESSRIGHTS_WRITER          40060
#define ID_ACCESSRIGHTS_READER          40061
#define ID_OVERLAP_KICK                 40062
#define ID_ACCESSRIGHTS_OUTSIDER        40063
#define IDC_FOUNDER                     40064
#define IDC_ADMIN                       40065
#define IDC_MODERATOR                   40066
#define IDC_MEMBER                      40067
#define IDC_WRITER                      40068
#define IDC_READER                      40069
#define IDC_OUTSIDER                    40070
#define ID_OVERLAP_SOUNDSIGNAL          40071
#define ID_OVERLAP_SOUNDSIGNAL40072     40072
#define IDS_SOUNDSIGNAL                 40073
#define ID_OVERLAP_ALERT                40074
#define IDC_ALERT                       40075
#define ID_OVERLAP_PRIVATEMESSAGE       40076
#define IDC_PRIVATEMESSAGE              40077
#define IDC_KICK                        40078
#define ID_OVERLAP_SENDCLIPBOARD        40080
#define IDC_CLIPBOARD                   40081
#define ID_OVERLAP_SAVEAS               40082
#define IDC_LOGSAVEAS                   40083
#define ID_OVERLAP_PRIVATE              40084
#define ID_OVERLAP_ANONYMOUS            40085
#define IDC_CHANPRIVATE                 40086
#define IDC_CHANANONYMOUS               40087
#define IDC_CHANHIDDEN                  40088
#define ID_OVERLAP_ENTRYSTATUS          40089
#define ID_OVERLAP_ENTRYSTATUS40090     40090
#define ID_ENTRYSTATUS_FOUNDER          40091
#define ID_ENTRYSTATUS_ADMINISTRATOR    40092
#define ID_ENTRYSTATUS_MODERATOR        40093
#define ID_ENTRYSTATUS_MEMBER           40094
#define ID_ENTRYSTATUS_WRITER           40095
#define ID_ENTRYSTATUS_WRITER40096      40096
#define ID_ENTRYSTATUS_WRITER40097      40097
#define ID_ENTRYSTATUS_READER           40098
#define ID_ENTRYSTATUS_PRIVATECHANNEL   40099
#define IDC_CHANFOUNDER                 40100
#define IDC_CHANADMIN                   40101
#define IDC_CHANMODERATOR               40102
#define IDC_CHANMEMBER                  40103
#define IDC_CHANWRITER                  40104
#define IDC_CHANREADER                  40105
#define ID_OVERLAP_JOIN                 40106
#define ID_OVERLAP_RENAME               40107
#define ID_OVERLAP_RENAME40108          40108
#define ID_OVERLAP_RENAME40109          40109
#define ID_OVERLAP_REFRESHLIST          40110
#define IDC_RENAME                      40111
#define ID_OVERLAP_TOPIC                40112
#define IDC_TOPIC                       40113
#define ID_OVERLAP_RENAME40114          40114

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        169
#define _APS_NEXT_COMMAND_VALUE         40115
#define _APS_NEXT_CONTROL_VALUE         1061
#define _APS_NEXT_SYMED_VALUE           102
#endif
#endif
